lib: [
  "_build/install/default/lib/nomad/META" {"META"}
  "_build/install/default/lib/nomad/opam" {"opam"}
  "_build/install/default/lib/nomad/nomad__Aux.cmi" {"nomad__Aux.cmi"}
  "_build/install/default/lib/nomad/nomad__Aux.cmx" {"nomad__Aux.cmx"}
  "_build/install/default/lib/nomad/nomad__Aux.cmt" {"nomad__Aux.cmt"}
  "_build/install/default/lib/nomad/aux.ml" {"aux.ml"}
  "_build/install/default/lib/nomad/nomad.cmi" {"nomad.cmi"}
  "_build/install/default/lib/nomad/nomad.cmx" {"nomad.cmx"}
  "_build/install/default/lib/nomad/nomad.cmt" {"nomad.cmt"}
  "_build/install/default/lib/nomad/nomad.ml-gen" {"nomad.ml-gen"}
  "_build/install/default/lib/nomad/nomad__Project.cmi" {"nomad__Project.cmi"}
  "_build/install/default/lib/nomad/nomad__Project.cmx" {"nomad__Project.cmx"}
  "_build/install/default/lib/nomad/nomad__Project.cmt" {"nomad__Project.cmt"}
  "_build/install/default/lib/nomad/project.ml" {"project.ml"}
  "_build/install/default/lib/nomad/nomad.cma" {"nomad.cma"}
  "_build/install/default/lib/nomad/nomad.cmxa" {"nomad.cmxa"}
  "_build/install/default/lib/nomad/nomad.a" {"nomad.a"}
  "_build/install/default/lib/nomad/nomad.cmxs" {"nomad.cmxs"}
  "_build/install/default/lib/nomad/nomad.dune" {"nomad.dune"}
]
bin: [
  "_build/install/default/bin/tests" {"tests"}
  "_build/install/default/bin/nomad" {"nomad"}
]
share: [
  "_build/install/default/share/nomad/templates/lib/%%NAME%%.opam" {"templates/lib/%%NAME%%.opam"}
  "_build/install/default/share/nomad/templates/lib/src/%%NAME%%.ml" {"templates/lib/src/%%NAME%%.ml"}
  "_build/install/default/share/nomad/templates/lib/src/jbuild" {"templates/lib/src/jbuild"}
  "_build/install/default/share/nomad/templates/lib/test/jbuild" {"templates/lib/test/jbuild"}
  "_build/install/default/share/nomad/templates/lib/test/tests.ml" {"templates/lib/test/tests.ml"}
  "_build/install/default/share/nomad/templates/lib/.gitignore" {"templates/lib/.gitignore"}
  "_build/install/default/share/nomad/templates/bin/%%NAME%%.opam" {"templates/bin/%%NAME%%.opam"}
  "_build/install/default/share/nomad/templates/bin/bin/main.ml" {"templates/bin/bin/main.ml"}
  "_build/install/default/share/nomad/templates/bin/bin/jbuild" {"templates/bin/bin/jbuild"}
  "_build/install/default/share/nomad/templates/bin/lib/%%NAME%%.ml" {"templates/bin/lib/%%NAME%%.ml"}
  "_build/install/default/share/nomad/templates/bin/lib/jbuild" {"templates/bin/lib/jbuild"}
  "_build/install/default/share/nomad/templates/bin/test/jbuild" {"templates/bin/test/jbuild"}
  "_build/install/default/share/nomad/templates/bin/test/tests.ml" {"templates/bin/test/tests.ml"}
  "_build/install/default/share/nomad/templates/bin/.gitignore" {"templates/bin/.gitignore"}
]
doc: [
  "_build/install/default/doc/nomad/README.org"
]
