Create an empty config to avoid searching into the runner environments file system

  $ mkdir .nomad && echo "()" > .nomad/config.sexp

Initialize a new executable

  $ echo '((author "Shon Feder") (username shonfeder))' > config.sexp
  $ nomad new --bin new_project --config config.sexp | grep "Done."
  Done.
  Done.
  Done.
  $ ls -a new_project
  .
  ..
  .git
  .gitignore
  .ocamlformat
  _build
  _opam
  bin
  dune-project
  lib
  new_project.opam
  test

We can build the project

  $ cd new_project && dune build

And the generated opam file has the expected contents

  $ cat new_project.opam
  # This file is generated by dune, edit dune-project instead
  opam-version: "2.0"
  synopsis: "Short description"
  description: "Longer description"
  maintainer: ["Shon Feder"]
  authors: ["Shon Feder"]
  license: "MIT"
  homepage: "https://github.com/shonfeder/new_project"
  bug-reports: "https://github.com/shonfeder/new_project/issues"
  depends: [
    "dune" {>= "2.9" & > "2.9"}
    "ocaml"
    "alcotest" {with-test}
    "qcheck" {with-test}
    "qcheck-alcotest" {with-test}
    "odoc" {with-doc}
  ]
  build: [
    ["dune" "subst"] {dev}
    [
      "dune"
      "build"
      "-p"
      name
      "-j"
      jobs
      "--promote-install-files=false"
      "@install"
      "@runtest" {with-test}
      "@doc" {with-doc}
    ]
    ["dune" "install" "-p" name "--create-install-files" name]
  ]
  dev-repo: "git+https://github.com/shonfeder/new_project.git"
